---
title: Erste Schritte mit Minecraft Pi
hero_image: images/banner.png
description: Hol dir deinen ersten Vorgeschmack auf die Programmierung der Welt von Minecraft
original_url: https://raspberrypi.org/learning/getting-started-with-minecraft-pi
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Einleitung
  - 
    title: Was du brauchen wirst
  - 
    title: Erste Schritte mit Minecraft Pi
  - 
    title: Minecraft öffnen
  - 
    title: Use the Python programming interface
  - 
    title: Dropping blocks as you walk
  - 
    title: Mit TNT-Blöcken spielen
  - 
    title: Spaß mit fließender Lava.
  - 
    title: Wie geht es weiter?
