---
title: Getting Started with Minecraft Pi
hero_image: images / banner.png
description: Get your first taste of programming the world of Minecraft
original_url: https://raspberrypi.org/learning/getting-started-with-minecraft-pi
theme: 노란
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, 디자인 -0, 프로그래밍 -2, phys-comp-0, 제조 -0, 커뮤니티 -0
interests: 게임
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: 소개
  - 
    title: 준비물
  - 
    title: Getting Started with Minecraft Pi
  - 
    title: Run Minecraft
  - 
    title: Use the Python programming interface
  - 
    title: Dropping blocks as you walk
  - 
    title: Playing with TNT blocks
  - 
    title: Fun with flowing lava.
  - 
    title: 더 나아가기
